### ISSUE TITLE
Cannot find colors.rasi

### ISSUE THREAD

**Issue by madhur** [umutsevdi/dotfiles#1]
Thanks for the wonderful dotfiles. I really like your setup.

I was trying to replicate the rofi configuration, but could not find the find `colors.rasi` in the `applets` folder.

I found `global.rasi`, but it does not seem to have color variables such as `@urgent` which are referred in powermenu applet.

**Comment by umutsevdi** [comment]
Thanks for your input. At first `colors.rasi` file only included stuff like the colour scheme. But over time I added other global variables such as fonts. So I changed its name to `global.rasi` because it made more sense. All rasi files have been updated to `global.rasi`. The only thing I forgot to change seems to be the README.md file. The `@urgent` state is not used in the powermenu, so it wouldn't make a difference. But again thanks for reminding those. I'll clear them all some time.

**Comment by umutsevdi** [comment]
Also, I've created another shell script which is like a wrapper for all of the applets. You can find it here: [applet launcher](https://github.com/umutsevdi/dotfiles/blob/master/bin/applet)

**Comment by madhur** [comment]
`@urgent` is referred in `config.rasi` which is inside `powermenu` folder.

**Comment by umutsevdi** [comment]
I mean the urgent state of Rofi is never triggered by the powermenu.sh

**Comment by madhur** [comment]
Rofi does not start until it resolves all the variables. I get the error

![image](https://user-images.githubusercontent.com/509431/174483928-ac4353c7-6a57-4db3-a9ab-8d0d999e0eb2.png)

**Comment by umutsevdi** [comment]
I have never gotten this error. But I updated it, so it should probably work.

**Comment by madhur** [comment]
Now its giving error on variable `bg-selected` and `border`

**Comment by madhur** [comment]
```
$ rofi -v                                                                                                                                                                                                                                                                                                                     (19:38) (eks-stage-v2/2vonkk)
Version: 1.7.3-11-geff3b86c (next)
```

**Comment by umutsevdi** [comment]
```
17:08:36 $ ~ → rofi -v
Version: 1.7.3
17:08:54 $ ~ → ./.dotfiles/applets/powermenu/launch.sh 
17:09:02 $ ~ → ./.dotfiles/applets/launcher/launch.sh 
Mode combi is not enabled. I have enabled it for now.
Please consider adding combi to the list of enabled modi: modi: [window,run,ssh,combi].
17:09:16 $ ~ → ./.dotfiles/applets/player/launch.sh 
```
I'm not getting any errors or warnings.

**Comment by madhur** [comment]
Perhaps it is reading the default `$HOME/.config/rofi/config.rasi` and that has those definitions?

**Comment by umutsevdi** [comment]
I don't have any default configs for rofi
